name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: compile
      run: ./compile_tests.sh

    - name: run tests
      run: ./build/fizzbuzz_tests
